build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/emazzotta/docker-nginx-lua:$CI_BUILD_REF_NAME .
    - docker push $DOCKER_REGISTRY/emazzotta/docker-nginx-lua:$CI_BUILD_REF_NAME
